version: "3"
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.prod
  nginx: 
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
         - 80:80
    volumes:
      - ./src:/usr/app/src
      - /usr/app/node_modules
    environment:
      - NEXT_PUBLIC_TEST=dockercompose
      - CHOKIDAR_USEPOLLING=true
    #env_file:
    #  - ./.env
