# Base on offical Node.js Alpine image
FROM node:15-alpine
WORKDIR /app
RUN yarn install --global pm2
COPY ./package*.json ./
RUN yarn install --production --legacy-peer-deps
COPY ./ ./
RUN yarn run build
EXPOSE 3001
USER node
CMD [ "pm2-runtime", "yarn", "--", "start" ]