# Base on offical Node.js Alpine image
FROM node:19-alpine
WORKDIR /app
RUN npm install --global pm2
COPY ./package*.json ./
RUN npm install --production --force 
COPY ./ ./
RUN npm run build
EXPOSE 3001
USER node
CMD [ "pm2-runtime", "npm", "--", "start" ]