# Base on official Node.js Alpine image
FROM alpine:3.16
# Install apk manually
RUN apk update && apk add --no-cache apk-tools

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy application code
COPY . .

# Expose the application port
EXPOSE 9091

# Set user as root
USER root

# Start the application with pm2
CMD ["pm2-runtime", "npm", "--", "start"]