# Base on official Node.js Alpine image
FROM node:15-alpine
# Install apk manually
RUN npm install --global pm2
RUN npx prisma generate
# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy application code
COPY . .

# Expose the application port
EXPOSE 9091

# Set user as root
USER root

# Start the application with pm2
CMD ["pm2", "start",  "src/index.js"]