
version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=db_user2
      - POSTGRES_PASSWORD=db_password2
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'